times = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico-PR', 'Atlético-MG',
         'Fortaleza','São Paulo','América-MG','Botafogo','Santos','Goiás','Red Bull Bragantino','Coritiba',
         'Cuiabá','Ceará','Atlético-GO','Avaí','Juventude')
print('='*40)
print('{:^40}'.format('Times do Brasileirão'))
print('='*40)
print(times)
print('='*40)
print('Os 5 primeiros times são: {}'.format(times[0:5]))
print('='*40)
print('Os ultimos 4 colocados são: {}'.format(times[-4:]))
print('='*40)
print('Equipes em ordem alfabetica: {}'.format(sorted(times)))
print('='*40)
print(f'A equipe Goiás aparece na {times.index("Goiás")+1}ª colocação!')
print('='*40)
print('='*40)
print('Fim do programa , nos vemos na proxima temporada!')
print('='*40)
print('='*40)
